### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by adrahon** [rakesh-patnaik/nagios-openstack-monitoring#4]
There's no license for the project, some files have a license embedded, but it's not clear what the license for the general project is.

**Comment by saintaardvark** [comment]
I'd like to second this; I'd love to use this at $WORK, but I can't do that if the license isn't clear.  If you're looking for suggestions, I'm a big fan of the GPL...but it's your work and your decision. :-)

**Comment by rakesh-patnaik** [comment]
hey guys, sorry for slacking out long on this one. I have put GPL license text on all plugin code and the README file. Please let me know if it works and feel free to change/redistribute/contribute on this repo. I will also create a contribution on nagios exchange linking to this repo. Thanks for booting this idea up.
